feat: styles 4-support tiles for sl1a4
newsuk/times-components-native pull request #319
Opened 2021-01-27 15:42 UTC by c-j-j

2021-02-02 13:28 UTC, c-j-j commented on packages/edition-slices/src/tiles/tile-lead-supplement-portrait/index.tsx
> +        headlineStyle={styles.headline}
Do you need to pass labelColor? I added this https://github.com/newsuk/times-components-native/pull/319/files#diff-8dff6d7ba109a162e8c886f615e10262f56ad292ff9f9ed53f806ad88471a082R61

2021-02-02 14:10 UTC, aronshamash commented on packages/edition-slices/src/tiles/tile-lead-supplement-portrait/index.tsx
> +        headlineStyle={styles.headline}
Waiting for UXD to confirm requirements

2021-02-03 14:05 UTC, aronshamash commented on packages/edition-slices/src/tiles/tile-lead-supplement-portrait/index.tsx
> +        headlineStyle={styles.headline}
assuming same as existing tiles which do not take a `labelColor`

2021-02-04 10:11 UTC, kamiranoff commented on packages/article-summary/src/article-summary.js
> +  style: PropTypes.oneOfType([
From memory, the propType is `number` if you use StyleSheet.create

2021-02-04 10:19 UTC, kamiranoff commented on packages/edition-slices/src/edition-slices.js
> +const isIOS = Platform.OS === "ios";
Not related to this PR but would it be useful to have this accessible globally?

2021-02-04 10:20 UTC, kamiranoff commented on packages/edition-slices/src/tiles/shared/tile-link.tsx
> +  style?: ViewStyle;
I thought that was the type for it `StyleProp<ViewStyle>`? Does it work as well?

2021-02-04 10:40 UTC, kamiranoff approved these changes

2021-02-04 13:40 UTC, c-j-j commented on packages/article-summary/src/article-summary.js
> +  style: PropTypes.oneOfType([
This is a `style` object - not sure I understand why it'll be `number`? It can be falsy, which is why I've had to add a boolean as a potential type.

2021-02-04 13:40 UTC, c-j-j commented on packages/edition-slices/src/edition-slices.js
> +const isIOS = Platform.OS === "ios";
Yes that would be useful as it is duplicated in quite a few places. But best to do in another PR as this is already getting pretty big

2021-02-04 13:42 UTC, c-j-j commented on packages/edition-slices/src/tiles/shared/tile-link.tsx
> +  style?: ViewStyle;
Ah you're right, ViewStyle is a single style object, whereas StyleProp can allow array of objects/false/etc

2021-02-04 13:44 UTC, c-j-j commented on packages/article-summary/src/article-summary.js
> +  style: PropTypes.oneOfType([
I think article-summary really needs to be converted to TS soon... where we can type these props correctly.

2021-02-04 13:59 UTC, justadamhopkins requested changes
Looks good one minor comment on consistency in the slice map

2021-02-04 13:59 UTC, justadamhopkins commented on packages/edition-slices/__tests__/tile-lead-supplement-landscape/tile-lead-supplement-landscape.base.js
> +};
i know this is the consistent pattern but a `test.each` would keep these files leaner

2021-02-04 13:59 UTC, justadamhopkins commented on packages/edition-slices/src/edition-slices.js
> +        : SupplementLeadOneAndFourSlice
Should you not break this out into a function below? like I did with the l2np2 sport variant?

2021-02-04 14:09 UTC, c-j-j commented on packages/edition-slices/__tests__/tile-lead-supplement-landscape/tile-lead-supplement-landscape.base.js
> +};
I do like `test.each` - but as you say it, will introduce inconsistency adding here. Potentially something we can do in a separate PR?

2021-02-04 14:14 UTC, c-j-j commented on packages/edition-slices/src/edition-slices.js
> +        : SupplementLeadOneAndFourSlice
Good call - I can do the others too so this main function reads a bit better.

2021-02-04 14:46 UTC, justadamhopkins approved these changes
LGTM!!

2021-02-04 16:16 UTC, merged